### ISSUE TITLE
MediaPlayer onPlayerSourceStateChanged wrong events sequence

### ISSUE THREAD

**Issue by bastengao** [AgoraIO-Extensions/react-native-agora-rtc-ng#9]
```
 LOG  onPlayerSourceStateChanged 1(Opening) 0
 LOG  onPlayerSourceStateChanged 2(OpenCompleted) 0
 LOG  play
 LOG  onPlayerSourceStateChanged 3(Playing) 0
 LOG  onPlayerSourceStateChanged 2(OpenCompleted) 0
```

call mediaPlayer.play() when state is `OpenCompleted`. But get `OpenCompleted` again after `Playing` state.

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by bastengao** [comment]
I use it in our project. And I register listener `onPlayerSourceStateChanged` on MediaPlayer, sometimes will got events in wrong order.

**Comment by LichKing-2234** [comment]
is it must appear?

**Comment by bastengao** [comment]
> is it must appear?

Sometimes on 4.0.0-beta.1

**Comment by LichKing-2234** [comment]
This repo has been migrated to https://github.com/AgoraIO-Extensions/react-native-agora
